package com.ecommerce.digitaltricks.enums.pedido;

public enum CupomErroCode {
    CUPOM_INVALIDO,
    CUPOM_NAO_ENCONTRADO,
    CUPOM_INATIVO,
    CUPOM_EXPIRADO,
    CARRINHO_VAZIO,
    VALOR_MINIMO_NAO_ATINGIDO,
    LIMITE_TOTAL_ATINGIDO,
    LIMITE_POR_USUARIO_ATINGIDO,
    TIPO_ENTREGA_NAO_PERMITIDO,
    TIPO_PAGAMENTO_NAO_PERMITIDO,
    EMPRESA_DIFERENTE,
    PRIMEIRA_COMPRA_OBRIGATORIA,
    USUARIO_NAO_ELEGIVEL,
    CATEGORIA_NAO_ELEGIVEL,
    PRODUTO_NAO_ELEGIVEL,
    HORARIO_NAO_PERMITIDO,
    DIA_SEMANA_NAO_PERMITIDO,
    BAIRRO_NAO_ELEGIVEL,
    CEP_NAO_ELEGIVEL,
    NAO_CUMULATIVO,
    REQUISITOS_NAO_ATENDIDOS
}